# Made by Wallee#8314/Red-exe-Engineer
# Thanks @Bigjango helping :p

Block = {
    "Air": [0, 0],
    "Stone": [1, 0],
    "Grass": [2, 0],
    "Dirt": [3, 0],
    "Cobblestone": [4, 0],
    "Wooden Planks": [5, 0],
    "Saplin":[6, 0],
    "Oak Saplin": [6, 0],
    "Spruce Saplin": [6, 1],
    "Birch Saplin": [6, 2],
    "Bedrock": [7, 0],
    "Water": [8, 0],
    "Water Stationary": [9, 0],
    "Lava": [10, 0],
    "Lava Staionary": [11, 0],
    "Sand": [12, 0],
    "Gravel": [13, 0],
    "Gold Ore": [14, 0],
    "Iron Ore": [15, 0],
    "Coal Ore": [16, 0],
    "Log": [17, 0],
    "Oak Log": [17, 0],
    "Spruce Log": [17, 1],
    "Birch Log": [17, 2],
    "Leaves": [18, 0],
    "Oak Leaves": [18, 0],
    "Spruce Leaves": [18, 1],
    "Birch Leaves": [18, 2],
    "Glass": [20, 0],
    "Lapis Lazuli Ore": [21, 0],
    "Lapis Lazuli Block": [22, 0],
    "Sandstone": [24, 0],
    "Chiseled Sandstone": [24, 1],
    "Smooth Sandstone": [24, 2],
    "Bed": [26, 0],
    "Bed Foot": [26, 0],
    "Bed Head": [26, 8],
    "North Bed Foot": [26, 0],
    "North Bed Head": [26, 8],
    "East Bed Foot": [26, 1],
    "East Bed Head": [26, 9],
    "South Bed Foot": [26, 2],
    "South Bed Head": [26, 10],
    "West Bed Foot": [26, 3],
    "West Bed Head": [26, 11],
    "Cobweb": [30, 0],
    "Shrub": [31, 0],
    "Tall Grass": [31, 1],
    "Fern": [31, 3],
    "Wool": [35, 0],
    "White Wool": [35, 0],
    "Orange Wool": [35, 1],
    "Magenta Wool": [35, 2],
    "Light Blue Wool": [35, 3],
    "Yello Wool": [35, 4],
    "Lime Wool": [35, 5],
    "Pink Wool": [35, 6],
    "Grey Wool": [35, 7],
    "Light Grey Wool": [35, 8],
    "Cyan Wool": [35, 9],
    "Purple Wool": [35, 10],
    "Blue Wool": [35, 11],
    "Brown Wool": [35, 12],
    "Green Wool": [35, 13],
    "Red Wool": [35, 14],
    "Black Wool": [35, 15],
    "Flower": [37, 0],
    "Poppy": [38, 0],
    "Brown Mushroom": [39, 0],
    "Red Mushroom": [40, 0],
    "Block of Gold": [41, 0],
    "Block of Iron": [42, 0],
    "Double Stone Slab": [43, 0],
    "Smooth Stone": [43, 6],
    "Stone Slab": [44, 0],
    "Sandstone Slab": [44, 1],
    "Wooden Slab": [44, 2],
    "Cobblestone Slab": [44, 3],
    "Bricks Slab": [44, 4],
    "Stone Bricks Slab": [44, 5],
    "Lower Stone Slab": [44, 0],
    "Lower Sandstone Slab": [44, 1],
    "Lower Wooden Slab": [44, 2],
    "Lower Cobblestone Slab": [44, 3],
    "Lower Bricks Slab": [44, 4],
    "Lower Stone Bricks Slab": [44, 5],
    "Upper Stone Slab": [44, 8],
    "Upper Sandstone Slab": [44, 9],
    "Upper Wooden Slab": [44, 10],
    "Upper Cobblestone Slab": [44, 11],
    "Upper Bricks Slab": [44, 12],
    "Upper Stone Bricks Slab": [44, 13],
    "Stone Slab Block": [43, 0],
    "Sandstone Slab Block": [43, 1],
    "Wooden Slab Block": [43, 2],
    "Cobblestone Slab Block": [43, 3],
    "Bricks Slab Block": [43, 4],
    "Stone Bricks Slab Block": [43, 5],
    "Smooth Stone": [43, 6],
    "Bricks": [45, 0],
    "TNT": [46, 0],
    "Active TNT": [46, 1],
    "Bookshelf": [47, 0],
    "Moss Stone": [48, 0],
    "Obsidian": [49, 0],
    "Torch": [50, 0],
    "Wooden Stairs": [53, 2],
    "North Lower Wooden Stairs": [53, 2],
    "East Lower Wooden Stairs": [53, 1],
    "South Lower Wooden Stairs": [53, 3],
    "West Lower Wooden Stairs": [53, 0],
    "North Upper Wooden Stairs": [53, 6],
    "East Upper Wooden Stairs": [53, 5],
    "South Upper Wooden Stairs": [53, 7],
    "West Upper Wooden Stairs": [53, 4],
    "Chest": [54, 2],
    "Blank Chest": [54, 1],
    "North Chest": [54, 2],
    "East Chest": [54, 5],
    "South Chest": [54, 3],
    "West Chest": [54, 4],
    "Diamond Ore": [56, 0],
    "Diamond Block": [57, 0],
    "Crafting Table": [58, 0],
    "Crops": [59, 0],
    "Crops 1": [59, 1],
    "Crops 2": [59, 2],
    "Crops 3": [59, 3],
    "Crops 4": [59, 4],
    "Crops 5": [59, 5],
    "Crops 6": [59, 6],
    "Crops 7": [59, 7],
    "Farmland": [60, 0],
    "Wet Farmland": [60, 1],
    "Furnace": [61, 0],
    "Active Furnace": [62, 0],
    "Sign": [63, 0],
    "Sign 0": [63, 0],
    "Sign 1": [63, 1],
    "Sign 2": [63, 2],
    "Sign 3": [63, 3],
    "Sign 4": [63, 4],
    "Sign 5": [63, 5],
    "Sign 6": [63, 6],
    "Sign 7": [63, 7],
    "Sign 8": [63, 8],
    "Sign 9": [63, 9],
    "Sign 10": [63, 10],
    "Sign 11": [63, 11],
    "Sign 12": [63, 12],
    "Sign 13": [63, 13],
    "Sign 14": [63, 14],
    "Sign 15": [63, 15],
    "Lower North Closed Wooden Door": [64, 1],
    "Lower North Opened Wooden Door": [64, 5],
    "Lower East Closed Wooden Door": [64, 2],
    "Lower East Opened Wooden Door": [64, 2],
    "Lower South Closed Wooden Door": [46, 3],
    "Lower South Opened Wooden Door": [64, 7],
    "Lower West Closed Wooden Door": [64, 0],
    "Lower West Opened Wooden Door": [64, 4],
    "Upper Left Wooden Door": [64, 8],
    "Upper Right  Wooden Door": [64, 9],
    "Lower Wooden Door": [64, 1],
    "Upper Wooden Door": [64, 8],
    "Ladder": [65, 2],
    "North Ladder": [65, 2],
    "East Ladder": [65, 5],
    "South Ladder": [65, 3],
    "West Ladder": [65, 4],
    "Cobblestone Stairs": [67, 2],
    "North Lower Cobblestone Stairs": [67, 2],
    "East Lower Cobblestone Stairs": [67, 1],
    "South Lower Cobblestone Stairs": [67, 3],
    "West Lower Cobblestone Stairs": [67, 0],
    "North Upper Cobbleston Stairs": [57, 6],
    "East Upper Cobbleston Stairs": [57, 5],
    "South Upper Cobbleston Stairs": [57, 7],
    "West Upper Cobbleston Stairs": [57, 4],
    "Wall Sign": [68, 2],
    "North Walle Sign": [68, 2],
    "East Wall Sign": [68, 5],
    "South Wall Sign": [68, 1],
    "West Wall Sign": [68, 4],
    "Lower North Closed Iron Door": [71, 1],
    "Lower North Opened Iron Door": [71, 5],
    "Lower East Closed Iron Door": [71, 2],
    "Lower East Opened Iron Door": [71, 2],
    "Lower South Closed Iron Door": [71, 3],
    "Lower South Opened Iron Door": [71, 7],
    "Lower West Closed Iron Door": [71, 0],
    "Lower West Opened Iron Door": [71, 4],
    "Upper Left Iron Door": [71, 8],
    "Upper Right  Iron Door": [71, 9],
    "Lower Iron Door": [71, 1],
    "Upper Iron Door": [71, 8],
    "Redstone Ore": [73, 0],
    "Snow": [78, 0],
    "Ice": [79, 0],
    "Snow Block": [80, 0],
    "Cactus": [81, 0],
    "Clay Block": [82, 0],
    "Suger Cane": [83, 0],
    "Fence": [85, 0],
    "Glowstone Block": [89, 0],
    "Invisible Bedrock": [95, 0],
    "Trapdoor": [96, 0],
    "North Closed Trapdoor": [96, 0],
    "East Closed Trapdoor": [96, 3],
    "South Closed Trapdoor": [96, 1],
    "West Closed Trapdoor": [96, 2],
    "North Opened Trapdoor": [96, 4],
    "East Opened Trapdoor": [96, 7],
    "South Opened Trapdoor": [96, 5],
    "West Opened Trapdoor": [96, 6],
    "Stone Bricks": [98, 0],
    "Mossy Stone Bricks": [98, 1],
    "Cracked Stone Bricks": [98, 2],
    "Glass Pane": [102, 0],
    "Melon": [103, 0],
    "Melon Stem": [105, 0],
    "Melon Stem 0": [105, 0],
    "Melon Stem 1": [105, 1],
    "Melon Stem 2": [105, 2],
    "Melon Stem 3": [105, 3],
    "Melon Stem 4": [105, 4],
    "Melon Stem 5": [105, 5],
    "Melon Stem 6": [105, 6],
    "Melon Stem 7": [105, 7],
    "Fence Gate": [107, 0],
    "North South Fence Gate": [107, 0],
    "South North Fence Gate": [107, 0],
    "East West Closed Fence Gate": [107, 3],
    "West West Closed Fence Gate": [107, 3],
    "North Opened Fence Gate": [107, 4],
    "East Opened Fence Gate": [107, 5],
    "South Opened Fence Gate": [107, 6],
    "West Opened Fence Gate": [107, 7],
    "Brick Stairs": [108, 2],
    "North Lower Brick Stairs": [108, 2],
    "East Lower Brick Stairs": [108, 1],
    "South Lower Brick Stairs": [108, 3],
    "West Lower Brick Stairs": [108, 0],
    "North Upper Brick Stairs": [108, 6],
    "East Upper Brick Stairs": [108, 5],
    "South Upper Brick Stairs": [108, 7],
    "West Upper Brick Stairs": [108, 4],
    "Stone Brick Stairs": [109, 2],
    "North Lower Stone Brick Stairs": [109, 2],
    "East Lower Stone Brick Stairs": [109, 1],
    "South Lower Stone Brick Stairs": [109, 3],
    "West Lower Stone Brick Stairs": [109, 0],
    "North Upper Stone Brick Stairs": [109, 6],
    "East Upper Stone Brick Stairs": [109, 5],
    "South Upper Stone Brick Stairs": [109, 7],
    "West Upper Stone Brick Stairs": [109, 4],
    "Nether Brick Stairs": [114, 2],
    "North Lower Nether Brick Stairs": [114, 2],
    "East Lower Nether Brick Stairs": [114, 1],
    "South Lower Nether Brick Stairs": [114, 3],
    "West Lower Nether Brick Stairs": [114, 0],
    "North Upper Nether Brick Stairs": [114, 6],
    "East Upper Nether Brick Stairs": [114, 5],
    "South Upper Nether Brick Stairs": [114, 7],
    "West Upper Nether Brick Stairs": [114, 4],
    "Sandstone Stairs": [128, 2],
    "North Lower Sandstone Stairs": [128, 2],
    "East Lower Sandstone Stairs": [128, 1],
    "South Lower Sandstone Stairs": [128, 3],
    "West Lower Sandstone Stairs": [128, 0],
    "North Upper Sandstone Stairs": [128, 6],
    "East Upper Sandstone Stairs": [128, 5],
    "South Upper Sandstone Stairs": [128, 7],
    "West Upper Sandstone Stairs": [128, 4],
    "Block of Quartz": [155, 0],
    "Chiseled Quartz Block": [155, 1],
    "Quartz Pillar": [155, 2],
    "Glowing Obsidian": [246, 0],
    "Nether Reactor Core": [247, 0],
    "Active Nether Reactor Core": [247, 1],
    "Used Nether Reactor Core": [247, 2],
    "Update": [248, 0],
    "Ateupd": [249, 0],
    "Held Grass": [253, 0],
    "Held Leaves": [254, 0],
    "Held Oak Leaves": [254, 0],
    "Held Spruce Leaves": [254, 1],
    "Held Birch Leaves": [254, 2],
    "Fire": [255, 0]
}

Item = {
    "Iron Shovel": 256,
    "Iron Pickaxe": 257,
    "Iron Axe": 258,
    "Flint and Steel": 259,
    "Apple": 260,
    "Bow": 261,
    "Arrow": 262,
    "Coal": 263,
    "Diamond": 264,
    "Iron Ingot": 265,
    "Gold Ingot": 266,
    "Iron Sword": 267,
    "Wooden Sword": 268,
    "Wooden Shovel": 269,
    "Wooden Pickaxe": 270,
    "Wooden Axe": 271,
    "Stone Sword": 272,
    "Stone Shovel": 273,
    "Stone Pickaxe": 274,
    "Stone Axe": 275,
    "Diamond Sword": 276,
    "Diamond Shovel": 277,
    "Diamond Pickace": 278,
    "Diamond Axe": 279,
    "Stick": 280,
    "Bowl": 281,
    "Mushroom Stew": 282,
    "Gold Sword": 283,
    "Gold Shovel": 284,
    "Gold Pickaxe": 285,
    "Gold Axe": 286,
    "String": 287,
    "Feather": 288,
    "Gunpowder": 289,
    "Wooden Hoe": 290,
    "Stone Hoe": 291,
    "Iron Hoe": 292,
    "Diamond Hoe": 293,
    "Gold Hoe": 294,
    "Seeds": 295,
    "Wheet": 296,
    "Bread": 297,
    "Leather Cap": 298,
    "Leather Tunic": 299,
    "Leather Pants": 300,
    "Leather Boots": 301,
    "Chain Helmet": 302,
    "Chain Chestplate": 303,
    "Chain Leggings": 304,
    "Chain Boots": 305,
    "Iron Helmet": 306,
    "Iron Chestplate": 307,
    "Iron Leggings": 308,
    "Iron Boots": 309,
    "Diamond Helmet": 310,
    "Diamond Chestplate": 311,
    "Diamond Leggings": 312,
    "Diamond Boots": 313,
    "Gold Helmet": 314,
    "Gold Chestplate": 315,
    "Gold Leggings": 316,
    "Gold Boots": 317,
    "Flint": 318,
    "Raw Porkchop": 319,
    "Cooked Porkchop": 320,
    "Painting": 321,
    "Sign": 323,
    "Wooden Door": 324,
    "Iron Door": 330,
    "Snowball": 332,
    "Leather": 334,
    "Brick": 336,
    "Clay": 337,
    "Sugar Cane": 338,
    "Paper": 339,
    "Book": 340,
    "Slimeball": 341,
    "Egg": 344,
    "Compass": 345,
    "Clock": 347,
    "Glowstone Dust": 248,
    "Dye": 351,
    "Bone": 352,
    "Sugar": 353,
    "Bed": 356,
    "Shears": 359,
    "Melon": 360,
    "Melon Seeds": 362,
    "Raw Beef": 363,
    "Steak": 364,
    "Raw Chicken": 365,
    "Cooked Chicken": 366,
    "Camera": 456
    }

def searchBlock(search="", printName=False):

    search = search.lower()
    IDs = []

    for block in Block:

        blockName = block.lower()

        if search in blockName:
            IDs.append([block, Block[block]])

            if printName == True:
                print(f'{block} ({Block[block]})')
    return(dict(IDs))

def searchItem(search="", printName=False):

    search = search.lower()
    IDs = []

    for item in Item:

        itemName = item.lower()

        if search in itemName:
            IDs.append([item, Item[item]])

            if printName == True:
                print(f'{item} ({Item[item]})')
    return(dict(IDs))

def searchAll(search="", printName=False):

    search = search.lower()
    IDs = []

    for block in Block:

        blockName = block.lower()

        if search in blockName:
            IDs.append([block, Block[block]])

            if printName == True:
                print(f'{block} ({Block[block]})')

    for item in Item:

        itemName = item.lower()

        if search in itemName:
            IDs.append([item, Item[item]])

            if printName == True:
                print(f'{item} ({Item[item]})')
    return(dict(IDs))


if __name__ == "__main__":
    searchFor = input("Search for a block or item: ")
    print(searchAll(search=searchFor))